# Site settings
title: "Rutgers USACS"
header_title: "USACS"
webmaster:      "Alexander Goodkind <alexander@goodkind.io>"
author: "Rutgers University Undergraduate Student Alliance of Computer Scientists"
description: "Rutgers University Undergraduate Student Alliance of Computer Scientists is the prominent undergraduate CS organization at Rutgers, faciliating the growth and network of Rutgers CS students."

baseurl:    "" # no trailing slash !
url:         "https://usacs.rutgers.edu"
date_format: "%-d.%m.%Y"

include: ['_pages']

collections:
  pages:
    output: true
    permalink: /:path

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      published: true
      order: 99

# include trailing slash !!!
favicon_path: "/assets/img/favicons/"  
css_path: "/assets/css/"
js_path: "/assets/js/"

# Google
google_analytics_tracking_code: "UA-124239918-1"
google_verification: ""
google_api_key: AIzaSyCKTQCRrJRfa70zK179sz1gvz0OXhCYvYM

mentors_spreadsheet_id: 1uBLzF5vNk3zsBQo3uC2VkAlDoTI4JOgM_26YA-ucLY8

# Facebook
facebook_app_id: ""

# Social
github_username: usacs
bitbucket_username:
stackoverflow_id:
twitter_username: rutgers_usacs
google_plus_id:
linkedin_username:
facebook_username: rutgers.usacs
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:
instagram_username: rutgers_usacs

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
